URL="https://osdn.net/dl/manjaro/manjaro-xfce-REPLACE_VERSION.iso"
TYPE=file
CONTENTS="\
manjaro/x86_64/livefs.sfs|livefs.sfs
manjaro/x86_64/rootfs.sfs|rootfs.sfs
boot/initramfs-x86_64.img|initrd
boot/vmlinuz-x86_64|vmlinuz"
EXTRACT_INITRD="true"
INITRD_NAME="initrd"
INITRD_TYPE="xz"
